server:
  port: 80

config:
  excel: D:\Workspace\github\cake_category\cake\src\main\resources\价格核算.xlsx

spring:
  datasource:
    #配置h2数据库的连接地址， 当前配置的是以文件方式连接
    url: jdbc:h2:file:./db/cake
    driver-class-name: org.h2.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapping:/*Mapper.xml
  type-aliases-package: com.sophia.cake.entity

logging:
  level:
    com:
      entity:
        mapper: debug
    root: info