insert into T_MATERIAL(CAPACITY, NAME, PRICE, PRICE_PER_UNIT, UNIT) VALUES ( 250, '总统黄油卷', 34.6, '克', 0.138);
insert into T_MATERIAL(CAPACITY, NAME, PRICE, PRICE_PER_UNIT, UNIT) VALUES ( 5000, '安佳大黄油5kg', 340, '克', 0.068);
insert into T_MATERIAL(CAPACITY, NAME, PRICE, PRICE_PER_UNIT, UNIT) VALUES ( 500, '柏扎莱发酵黄油', 34.6, '克', 0.072);
insert into T_MATERIAL(CAPACITY, NAME, PRICE, PRICE_PER_UNIT, UNIT) VALUES ( 1000, '安佳奶油', 44, '克', 0.044);
insert into T_MATERIAL(CAPACITY, NAME, PRICE, PRICE_PER_UNIT, UNIT) VALUES ( 1000, '总统奶油', 48, '克', 0.048);
insert into T_MATERIAL(CAPACITY, NAME, PRICE, PRICE_PER_UNIT, UNIT) VALUES ( 1000, '金钻奶油', 21, '克', 0.021);
insert into T_MATERIAL(CAPACITY, NAME, PRICE, PRICE_PER_UNIT, UNIT) VALUES ( 30000, '韩国细砂糖', 280, '克', 0.009);


insert into T_MATERIAL_FORMULA(COUNT, PRICE) VALUES ( 45, 3.06);
insert into T_MATERIAL_FORMULA(COUNT, PRICE) VALUES ( 25, 1.70);
insert into T_MATERIAL_FORMULA(COUNT, PRICE) VALUES ( 37, 2.52);
insert into T_MATERIAL_FORMULA(COUNT, PRICE) VALUES ( 45, 3.06);
insert into T_MATERIAL_FORMULA(COUNT, PRICE) VALUES ( 150, 3.00);
insert into T_MATERIAL_FORMULA(COUNT, PRICE) VALUES ( 300, 6.00);

insert into T_BASIC_FORMULA(COUNT, PRICE) VALUES ( 145, 7.06);
insert into T_BASIC_FORMULA(COUNT, PRICE) VALUES ( 35, 1.74);
insert into T_BASIC_FORMULA(COUNT, PRICE) VALUES ( 47, 2.72);
insert into T_BASIC_FORMULA(COUNT, PRICE) VALUES ( 35, 3.16);
insert into T_BASIC_FORMULA(COUNT, PRICE) VALUES ( 10, 4.00);
insert into T_BASIC_FORMULA(COUNT, PRICE) VALUES ( 30, 9.00);



INSERT INTO T_MIDDLE(name, price) VALUES ( '奶油纸杯蛋糕', 28.55);
INSERT INTO T_MIDDLE(name, price) VALUES ( '蛋白糖装饰蛋糕', 4.9);
INSERT INTO T_MIDDLE(name, price) VALUES ( '六寸加高艺术蛋糕', 44.23);
