server:
  port: 80

config:
  excel: D:\Workspace\cake_category\java\src\main\resources\价格核算.xlsx
  charset: UTF-8
  material: material.db
  materialProduct: material_product.db
  basic: basic.db
  basicProduct: basic_product.db
  middle: middle.db
logging:
  level:
    root: info

spring:
  datasource:
    #配置h2数据库的连接地址， 当前配置的是以文件方式连接
    url: jdbc:h2:file:./db/cake
    driver-class-name: org.h2.Driver
    username: root
    password: root

  jpa:
    #启用SQL语句的日志记录
    show-sql: false
    hibernate:
      #设置ddl模式
      ddl-auto: update