server:
  port: 80
config:
  excel: D:\Workspace\cake_category\java\src\main\resources\价格核算.xlsx
  charset: UTF-8
  material: material.db
  materialProduct: material_product.db
  basic: basic.db
  basicProduct: basic_product.db
  middle: middle.db
logging:
  level:
    root: info